import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider as NextThemeProvider } from "next-themes";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "@/components/ui/toaster";

// Satoshi Font (for body text)
const satoshi = localFont({
  src: "./fonts/SatoshiVariable.ttf", // path is relative to /app/layout.tsx
  variable: "--font-satoshi",
  weight: "100 200 300 400 500 600 700 800 900",
  display: "swap",
});

// Clash Display (for headings/hero)
const clashDisplay = localFont({
  src: "./fonts/ClashDisplayVariable.ttf",
  variable: "--font-clash-display",
  weight: "200 300 400 500 600 700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Shiptrack | Order Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${clashDisplay.variable} antialiased bg-light-light-gray dark:bg-dark-background`}
      >
        <AuthProvider>

        <NextThemeProvider attribute="class">
          <main>{children}</main>
        </NextThemeProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
